# Generated by Django 4.0.3 on 2022-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='food_items',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.fooditem'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(related_name='tags', to='recipes.recipe'),
        ),
    ]
