# Generated by Django 4.0.3 on 2022-06-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='directions',
        ),
    ]
